### PR TITLE
DOC: additional doctr command

### PR DESCRIPTION
**Pull request by ke-zhang-rd**

### CODE REVIEW

**Comment by danielballan** [comment]
There are lots of useful things one can do with doctr; to learn more, users should consult the doctr docs.

I would like to avoid making this docs too lengthy and also avoid creating more places that our documentation of doctr might get out of date. I am against this but would not raise strong objections if others think that it is worth adding.

**Comment by ke-zhang-rd** [comment]
> There are lots of useful things one can do with doctr; to learn more, users should consult the doctr docs.
> 
> I would like to avoid making this docs too lengthy and also avoid creating more places that our documentation of doctr might get out of date. I am against this but would not raise strong objections if others think that it is worth adding.

What if I just put this extra command as a comment in example doctr yml file?

**Comment by danielballan** [comment]
Personally, I don't see much of a difference between putting in prose and putting in the file. Both add marginal complexity and the possibility of becoming wrong.

**Comment by tacaswell** [comment]
I lean towards a link to the doctr docs rather than an example.  We should give users enough to work and whet their appetite, but do not need to give them a further sub-set of things that were useful to us.

**Comment by ke-zhang-rd** [comment]
Previous doctr link was broken.

**Comment by danielballan** [comment]
Thanks for the link fix, @ke-zhang-rd.

**Pull request merged**
