### PR TITLE
Remove filename spaces in template to avoid confusing git

### PR DESCRIPTION
**Pull request by MikeHart85**
As discussed with @danielballan 

I think the reason for the warnings/errors thrown by git when cloning the repo or using some git commands (the first `git status` for example) is because `.gitattributes` is space separated and gets confused by filenames with spaces. 

Unfortunately, it's also very awkward to escape spaces in that file. You have to use a `[[:space:]]` or `[[:blank:]]` placeholder, but those also match other types of whitespace, not just spaces. See here:

- https://stackoverflow.com/questions/18864698/whitespace-in-gitattributes-patterns
- https://stackoverflow.com/questions/52508887/how-do-i-define-a-gitattributes-rule-for-a-file-with-spaces-in-it

Needs to be tested to make sure removing the space from the template didn't break anything.

### CODE REVIEW

**Comment by MikeHart85** [comment]
Testing the effect of this is kind of awkward, as the error only shows up under certain conditions.

It always shows up when cloning, but only the first time you run `git status`. Haven't found as easy way to repeatedly trigger it, apart from deleting the repo and cloning it again. Would be great to know why the first `git status` is different from subsequent ones... maybe there's a way to "reset" it?

**Comment by MikeHart85** [comment]
Found a better way to test this:

```bash
(on master)

(bad behavior)
$ cd \{\{\ cookiecutter.repo_name\ \}\}/\{\{\ cookiecutter.package_dir_name\ \}\}/
$ git check-attr export-subst _version.py
}}/_version.py is not a valid attribute name: {{ cookiecutter.repo_name }}/.gitattributes:1
_version.py: export-subst: unspecified

(using [[:space:]] placeholder to fix it)
$ echo '{{[[:space:]]cookiecutter.package_dir_name[[:space:]]}}/_version.py export-subst' > ../.gitattributes 

(correct behavior)
$ git check-attr export-subst _version.py
_version.py: export-subst: set
$ git check-attr export-subst __init__.py
__init__.py: export-subst: unspecified
```

On this branch, I removed the spaces instead of using the placeholder, but this should still result in correct behavior. I suspect using the placeholder would break the template functionality?

**Comment by MikeHart85** [comment]
That one doesn't seem to be causing any problems for git (since it doesn't show up in any `.gitattributes`), but it might be a good idea to change it for consistency as well?

Should I change it too?

**Comment by danielballan** [comment]
> I suspect using the placeholder would break the template functionality?

I think so.

I wonder if the _only_ change you need to make is to `.gitattributes`; I don't know if you even need to move any files. `{{ cookiecutter.blah_blah }}` and `{{cookiecutter.blah_bah}}` are the same once `cookiecutter` has been applied.

**Comment by MikeHart85** [comment]
I think you're right... something just felt wrong about changing the reference to the filename without changing the filename to match. But both will be overwritten with the same thing, regardless, before that attribute becomes relevant. 

So it really shouldn't make any functional difference. Which forces us to make a choice with no obvious right answer:

1. Remove spaces only in file reference in `.gitattributes` (least invasive?)
1. Remove spaces from file reference and file referenced (current state)
1. Remove spaces from all `{{templates}}` (most consistent?)

Which way would you prefer?

**Comment by danielballan** [comment]
As much as I'm a fan of updating things all at once to keep them consistent, (3) seems worryingly invasive and also somewhat against typical jinja style. I am ambivalent between (1) and (2), happy to defer to your taste.

**Comment by MikeHart85** [comment]
Let's go with (1) then, since it is least invasive, and doesn't encroach on Jinja style, and as this is really just a workaround for a rather odd `.gitattributes` limitation.

**Comment by danielballan** [comment]
Confirmed that this removed the warning from git.

Cloning `master` gives warnings:

```
$ git clone git@github.com:NSLS-II/scientific-python-cookiecutter
Cloning into 'scientific-python-cookiecutter'...
<snipped>
}}/_version.py is not a valid attribute name: {{ cookiecutter.repo_name }}/.gitattributes:1
$ cd scientific-python-cookiecutter/
$ git status
}}/_version.py is not a valid attribute name: {{ cookiecutter.repo_name }}/.gitattributes:1
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Cloning this branch specifically does not:

```
$ git clone -b git_attributes_warning git@github.com:NSLS-II/scientific-python-cookiecutter
Cloning into 'scientific-python-cookiecutter'...
<snipped>
$ cd scientific-python-cookiecutter/
$ git status
On branch git_attributes_warning
Your branch is up to date with 'origin/git_attributes_warning'.

nothing to commit, working tree clean
```

Also, versioneer is still doing its thing sync-ing {package}.__version__ and the setuptools-reported version to the git tag:

```
19:50 $ cookiecutter https://github.com/NSLS-II/scientific-python-cookiecutter --checkout git_attributes_warning
You've downloaded /home/dallan/.cookiecutters/scientific-python-cookiecutter before. Is it okay to delete and re-download it? [yes]: 
full_name [Name or Organization]: 
email []: 
github_username []: 
project_name [Your Project Name]: stuff
package_dist_name [stuff]: 
package_dir_name [stuff]: 
repo_name [stuff]: 
project_short_description [Python package for doing science.]: 
year [2020]: 
Select minimum_supported_python_version:
1 - 3.6
2 - 3.7
3 - 3.5
4 - 3.4
Choose from 1, 2, 3, 4 (1, 2, 3, 4) [1]: 
$ cd stuff/
$ git init
$ git add .
$ git commit -am "initial commit"
<snipped>
$ git tag -a v0.0.1
$ pip install -e .
<snipped>
$ python -c "import stuff; print(stuff.__version__);"
0.0.1
$ python setup.py sdist
<snipped>
$ ls dist/
stuff-0.0.1.tar.gz
```

Thanks, @MikeHart85!

**Pull request merged**
